version: '3.5' 

services: 

    forecaster-ubuntu: 
      build: . 
      volumes: 
        - ./R:/usr/forecaster/R
      container_name: forecaster
      ports:
        - 5000:5000
      environment:
        - PORT=5000